vars:
  - url:
      train: https://huggingface.co/datasets/pirocheto/phishing-url/resolve/main/data/train.parquet
      test: https://huggingface.co/datasets/pirocheto/phishing-url/resolve/main/data/test.parquet

stages:
  download_data:
    cmd: 
      - mkdir -p data
      - wget ${url.train} -O ${data.train} -q --show-progress
      - wget ${url.test} -O ${data.test} -q --show-progress
    deps:
      - ${url.train}
      - ${url.test}
    outs:
      - data

  optimize:
    cmd: python src/optimize.py
    params:
      - data.train
      - train
    deps:
      - src/optimize.py
      - ${data.train}
    plots:
      - live/images/optimization_history.png:
          cache: false
    outs:
      - live/hyperparams.yaml:
          cache: False

  train:
    cmd: python src/train.py
    params:
      - data.train
      - train
      - model.pickle
    deps:
      - src/train.py
      - ${data.train}
      - live/hyperparams.yaml
    outs:
      - ${model.pickle}

  evaluate:
    cmd: python src/evaluate.py
    params:
      - data.test
      - model.pickle
    deps:
      - ${model.pickle}
      - src/evaluate.py
      - ${data.test}
    plots:
      - live/images/calibration_curve.png:
          cache: false
      - live/images/confusion_matrix.png:
          cache: false
      - live/images/precision_recall_curve.png:
          cache: false
      - live/images/roc_curve.png:
          cache: false
      - live/images/score_distribution.png:
          cache: false
    metrics:
      - live/metrics.json:
          cache: false

  create_onnx:
    cmd: python src/create_onnx.py
    deps:
      - ${model.pickle}
      - src/create_onnx.py
    outs:
      - ${model.onnx}

  modelcard:
    cmd: python src/modelcard.py
    deps:
      - resources/templates/modelcard.md.j2
      - resources/snippets
      - live/metrics.json
      - src/modelcard.py
    outs:
      - live/model/README.md:
          cache: false